### ISSUE TITLE
Accurate worker count

### ISSUE THREAD

**Issue by Nugine** [laizy/waitgroup-rs#4]
Is there any way to get accurate worker count?
I have a simple implementation but it is basicly a rewrite of Arc and uses lots of unsafe code (maybe incorrect).
If you are interested in the impl, I would open a PR to discuss it.

**Comment by laizy** [comment]
see #5

**Comment by laizy** [comment]
Close since `poll` use `Pin<&mut Self>`, it will not be called concurrently with `workers`, so the strong count is accurate. 

BTW: If your are interested, there is a `remove_atomic_waker` branch created 2 years ago, it has unsafe code, and needs some undocumented details in `Arc` to prove the correctness.   see : https://zhuanlan.zhihu.com/p/463779910

**Comment by Nugine** [comment]
Here is my idea. This commit replaces Arc with a slightly different design. 
<https://github.com/Nugine/waitgroup-rs/commit/22428cb3babc92b901da80b315f664cea6cad644> (about 200 loc)

When the strong count decreases to:
+ `1`  call the waker. If there is a `WaitFuture`, then it will be waked.
+ `0`  deallocate.

Thus we can remove the weak count and provide an accurate count of `Working` at any time. 
I'm not sure whether there is any memory ordering bug.
